<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6261" started-at="2018-01-14T22:18:43Z" finished-at="2018-01-14T22:18:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6261" started-at="2018-01-14T22:18:43Z" finished-at="2018-01-14T22:18:49Z">
      <class name="com.affilomnia.leadbaskets.BuyerTest">
        <test-method status="PASS" signature="before()[pri:0, instance:com.affilomnia.leadbaskets.BuyerTest@578a5ce8]" name="before" is-config="true" duration-ms="21" started-at="2018-01-15T00:18:43Z" finished-at="2018-01-15T00:18:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="testBuyerRegistrtion()[pri:0, instance:com.affilomnia.leadbaskets.BuyerTest@578a5ce8]" name="testBuyerRegistrtion" duration-ms="6117" started-at="2018-01-15T00:18:43Z" finished-at="2018-01-15T00:18:49Z">
          <exception class="java.lang.reflect.UndeclaredThrowableException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.UndeclaredThrowableExceptionat com.sun.proxy.$Proxy12.download(Unknown Source)at Pages.BuyerPage.integrationPage(BuyerPage.java:227)at com.affilomnia.leadbaskets.BuyerTest.testBuyerRegistrtion(BuyerTest.java:50)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failureat sun.security.ssl.Alerts.getSSLException(Unknown Source)at sun.security.ssl.Alerts.getSSLException(Unknown Source)at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)at com.codeborne.selenide.impl.DownloadFileWithHttpRequest.executeHttpRequest(DownloadFileWithHttpRequest.java:90)at com.codeborne.selenide.impl.DownloadFileWithHttpRequest.download(DownloadFileWithHttpRequest.java:56)at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:29)at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:18)at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)... 28 more]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.UndeclaredThrowableException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBuyerRegistrtion -->
      </class> <!-- com.affilomnia.leadbaskets.BuyerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
